name: Draft Release

on:
  push:
    branches:
      - main
      - master

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # Drafts your next Release notes as Pull Requests are merged
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: draft_release.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
