name: Publish Release

on:
  release:
    types:
      - published

jobs:
  publish-npm:
    # Only run if release is a prod release
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          check-latest: true
      - name: npm install
        run: npm install
      - name: npm version and publish
        run: |
          npm version ${{ github.event.release.tag_name }} --no-git-tag-version
          echo "//registry.npmjs.org/:_authToken=$NPM_API_TOKEN" >> ~/.npmrc
          npm publish --access public
        env:
          NPM_API_TOKEN: ${{ secrets.NPM_API_TOKEN }}
      - name: Upload Standalone Bundle Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/BandwidthRtc.bundle.js
          asset_name: BandwidthRtc.bundle.js
          asset_content_type: application/javascript

